function flight_result = export_flight_data(flight_setting, flight_data, time)
    global dispersion_input_file dispersion_output_file
    
    % Calling python function
    flight_result = py.export_flight_data.export_flight_data( ...
        flight_setting, ...
        flight_data, ...
        time, ...
        dispersion_input_file, ...
        dispersion_output_file ...
        );
end